name = "percy-memory"
main = "src/index.ts"
compatibility_date = "2026-02-02"

[[kv_namespaces]]
binding = "percy_memory"
id = "b1bc773a30484a07a053c5a2ad164271"

[vars]
API_KEY = "pmem_aaff3d307632411d9d4609507ec403ab"
